# Generated by Django 3.1.4 on 2020-12-12 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='board', to='users.User')),
            ],
        ),
    ]
