# Generated by Django 3.1.4 on 2020-12-12 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.IntegerField(default=None)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card', to='list.list')),
                ('members', models.ManyToManyField(related_name='card', to='users.User')),
            ],
        ),
    ]
